### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by Immortalin** [kyasu/android_vendor_samsung_ks01ltexx#1]
Thanks for creating this! Do you think you can add some build instructions and a list of changes that you have made?

**Comment by kyasu** [comment]
Build configuration is: https://github.com/kyasu/android_device_samsung_ks01lte/blob/cm-13.0/README
Build instructions is same as the CM: https://wiki.cyanogenmod.org/w/Build_for_ks01lte
Changes are: https://github.com/kyasu/android_device_samsung_ks01lte/commits/cm-13.0
Thanks.
